DELETE http://localhost:3001/api/persons/61528ff03359bb4413017550
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/61528ff03359bb4413017550
###
GET http://localhost:3001/info
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "00-000-0000"
}
###
PUT http://localhost:3001/api/persons/61528dce034eea18c97f40e8
Content-Type: application/json

{
    "number": "98-12-231980"
}
###
DELETE https://agile-wave-01036.herokuapp.com/api/persons/1
###
GET https://agile-wave-01036.herokuapp.com/api/persons
###
GET https://agile-wave-01036.herokuapp.com/api/persons/2
###
POST https://agile-wave-01036.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "98-12-231042"
}
###
POST https://agile-wave-01036.herokuapp.com/api/persons
Content-Type: application/json

{
    "number": "98-12-231042"
}