DELETE http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "98-12-231042"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "98-12-231042"
}